###Post transitrequest
POST localhost:3000/transit-request/1 HTTP/2
Content-Type: application/json

{
  "offeredCoins": 200,
  "requestedSeats": 2,
  "text": "Ich muss hier weg!!1!"
}


###Get pending transitrequests
GET localhost:3000/transit-request/all HTTP/2


###Put transitrequest
PUT localhost:3000/transit-request/update-params/1 HTTP/2
Content-Type: application/json

{
  "offeredCoins": 250,
  "requestedSeats": 1,
  "text": "Ich muss hier weg!!1! Dringend!!!"
}


###Accept transitrequest
PUT localhost:3000/transit-request/accept/5 HTTP/2


###Delete transitrequests
DELETE localhost:3000/transit-request/5 HTTP/2


