###Post transitrequest
POST localhost:3000/transit-request/2 HTTP/2
Content-Type: application/json

{
  "offeredCoins": 200
}


###Get pending transitrequests
GET localhost:3000/transit-request/all HTTP/2


###Put transitrequest
PUT localhost:3000/transit-request/2 HTTP/2
Content-Type: application/json

{
  "offeredCoins": 250
}