### Trip Request Offer
POST localhost:3000/request HTTP/2
Content-Type: application/json

{
  "startPlz": {
    "plz": "63679",
    "location": "Nidda"
  },
  "endPlz": {
    "plz": "35390",
    "location": "Gießen"
  },
  "description": "Das ist ein Test!",
  "startDate": "2024-02-18",
  "seats": 1
}

### Trip Request Offer
POST localhost:3000/request/offering/2 HTTP/2
Content-Type: application/json

{
  "requestedCoins": 1100,
  "text": "Wann soll ich da sein?"
}

### Test Search
GET localhost:3000/request/search?search=&fromPLZ=63679&toPLZ=63675&seats=2&date=2020-12-12&rating=4

### Test Search
GET localhost:3000/request/search?search=gießen&fromPLZ=63679&toPLZ=63675