### POST Offer
POST localhost:3000/offer HTTP/2
Content-Type: application/json

{
  "route": [
    {
      "plz": 63679
    },
    {
      "plz": 64002
    },
    {
      "plz": 35290
    }
  ],
  "vehicle": "test",
  "description": "Das ist ein Test!",
  "startDate": "2024-02-18"
}


### PUT Offer
PUT localhost:3000/offer/1 HTTP/2
Content-Type: application/json

{
  "route": [
    {
      "plz": 63679
    },
    {
      "plz": 64002
    },
    {
      "plz": 30390
    }
  ],
  "description": "Das ist ein geupdateter Test!",
  "startDate": "2024-02-19"
}