### POST Offer
POST localhost:3000/offer HTTP/2
Content-Type: application/json

{
  "route": [
    {
      "plz": 63679
    },
    {
      "plz": 64002
    },
    {
      "plz": 35290
    }
  ],
  "vehicle": "test",
  "description": "Das ist ein Test!",
  "startDate": "2024-02-18"
}


### PUT Offer
PUT localhost:3000/offer/props/1 HTTP/2
Content-Type: application/json

{
  "route": [
    {
      "plz": 63679
    },
    {
      "plz": 64002
    },
    {
      "plz": 30390
    }
  ],
  "description": "Das ist ein geupdateter Test!",
  "startDate": "2024-02-19"
}

### Get All Offers
GET localhost:3000/offer HTTP/2


### search offers
GET localhost:3000/offer/search/test HTTP/2


### Get own Offers
GET localhost:3000/offer/own HTTP/2

### Delete offer
DELETE localhost:3000/offer/delete/1 HTTP/2

