### Get Logged In User
GET localhost:3000/user HTTP/2

### POST User
POST localhost:3000/user HTTP/2
Content-Type: application/json

{
  "eMail": "vnxyz312@gmail.com",
  "firstName" : "Vincent",
  "lastName": "Neeb",
  "password": "1234",
  "birthday": "2002-02-18",
  "phoneNumber": "+49 173 55555"
}

### Update User
PUT localhost:3000/user HTTP/2
Content-Type: application/json

{
  "eMail": "vnxyz312@gmail.com",
  "firstName" : "Vincent",
  "lastName": "Schneeb",
  "birthday": "2002-02-19",
  "password": "1234"
}

### Delete logged in User
DELETE localhost:3000/user HTTP/2


### POST second User
POST localhost:3000/user HTTP/2
Content-Type: application/json

{
  "eMail": "sdakkwd@gmail.com",
  "firstName" : "maxi",
  "lastName": "Musterfrau",
  "password": "1234",
  "birthday": "2002-02-18",
  "phoneNumber": "+49 173 55555"
}


### POST third User
POST localhost:3000/user HTTP/2
Content-Type: application/json

{
  "eMail": "bruh@gmail.com",
  "firstName" : "Bruh",
  "lastName": "Scetta",
  "password": "1234",
  "birthday": "2002-02-18",
  "phoneNumber": "+49 173 55555"
}