name: deploy

on:
  workflow_run:
    workflows: [ validation ]
    types: [ completed ]


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: alex-ac/github-action-ssh-docker-compose@master
        name: Docker-Compose Remote Deployment
        with:
          ssh_host: ${{ secrets.DEVELOPMENT_TEST_SERVER_IP }}
          ssh_private_key: ${{ secrets.DEVELOPMENT_TEST_SERVER_SSH }}
          ssh_user: ${{ secrets.DEVELOPMENT_TEST_SERVER_USER }}
          docker_compose_prefix: cargonaut