name: validation

on:
  push:
    branches:
      - main


jobs:
  test-and-lint-nestJs:
    name: test the the backend with jest-ts
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"
          cache-dependency-path: |
            backend/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: "./backend"

      - name: Run Tests
        run: npm test
        working-directory: "./backend"

      - name: Run Lint
        run: npm run lint
        working-directory: "./backend"

  reject-push-on-error:
    runs-on: ubuntu-latest
    needs: test-and-lint-nestJs
    steps:
      - name: Check for test or lint errors
        run: echo "Check for errors"

      - name: Reject push on error
        if: failure()
        run: |
          echo "Error: Tests or linting failed. Please fix the issues before pushing."
          exit 1
